# Build and deploy web site
#   Requres a service connection "wildconsulting_ftp" to the FTP target
# 
# https://subhankarsarkar.com/dot-net6-azure-web-app-deployment-using-azure-devops-pipeline/
#

trigger:
- master

pr: none # Disable PR trigger

variables:
  buildConfiguration: 'Release'
  buildPoolVmImage: 'ubuntu-latest'
  dotNetFramework: 'net8.0'
  dotNetVersion: '8.0.x'
  #targetRuntime: 'linux-x64'
  targetRuntime: 'win-x86'
  ftpServerEndpoint: 'wildconsulting_ftp'

stages:

- stage: Build

  variables:
  - group: WildConsultingWebAppSettings

  jobs:
  - job: Build
    displayName: 'Build website'
    pool:
      vmImage:  $(buildPoolVmImage)
    steps:
    - task: UseDotNet@2
      displayName: 'Install .Net SDK'
      inputs:
        packageType: 'sdk'
        version: $(dotNetVersion)

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'
        noCache: true

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)  --no-restore'

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/*.Tests.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish as self-contained application
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --framework $(dotNetFramework) --runtime $(targetRuntime) --self-contained --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True

    - task: FileTransform@2
      displayName: 'Transform appsettings'
      inputs:
        folderPath: '$(Build.ArtifactStagingDirectory)/**/*.zip'
        xmlTransformationRules: ''
        jsonTargetFiles: '**/appsettings.json'

    - task: PublishBuildArtifacts@1
      displayName: Package and upload as a build artifact
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'wildconsultingweb'

- stage: Deploy

  variables:
  - group: WildConsultingDeploymentSettings

  jobs:
  - deployment: Deploy
    pool:
      vmImage:  $(buildPoolVmImage)
    environment: 'wildconsulting-web-env'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ExtractFiles@1
            displayName: 'Extract files'
            inputs:
              archiveFilePatterns: "$(agent.builddirectory)/**/*.zip"
              destinationFolder: '$(Pipeline.Workspace)/files'

          - task: PowerShell@2
            displayName: 'Create app_offline.htm'
            inputs:
              targetType: 'inline'
              script: |
                $offlineFilePath = "$(Pipeline.Workspace)/offline/app_offline.htm"
                $content = @"
                <html>
                  <head>
                    <title>Site Under Maintenance</title>
                  </head>
                  <body>
                    <h1>We'll be back soon!</h1>
                    <p>Sorry for the inconvenience but we're updating our website. We'll be back online very soon.</p>
                  </body>
                </html>
                "@
                New-Item -Path $(Pipeline.Workspace) -Name offline -ItemType Directory
                $content | Out-File -FilePath $offlineFilePath -Encoding utf8 -Force

          - task: FtpUpload@2
            displayName: 'Copy app_offline.htm file to tell server we are going offline'
            inputs:
              credentialsOption: 'serviceEndpoint'
              serverEndpoint: $(ftpServerEndpoint)
              rootDirectory: '$(Pipeline.Workspace)/offline'
              filePatterns: 'app_offline.htm' 
              remoteDirectory: /httpdocs/
              cleanContents: false
              preservePaths: true

          - task: FtpUpload@2
            displayName: 'Clean and copy app_offline.htm file again'
            inputs:
              credentialsOption: 'serviceEndpoint'
              serverEndpoint: $(ftpServerEndpoint)
              rootDirectory: '$(Pipeline.Workspace)/offline'
              filePatterns: 'app_offline.htm' 
              remoteDirectory: /httpdocs/
              cleanContents: true
              preservePaths: true
            # Add retries in case the clean operation fails due to file locks
            retryCountOnTaskFailure: 3

          - task: FtpUpload@2
            displayName: 'FTP Upload'
            inputs:
              credentialsOption: 'serviceEndpoint'
              serverEndpoint: $(ftpServerEndpoint)
              rootDirectory: '$(Pipeline.Workspace)/files'
              remoteDirectory: /httpdocs/
              # No need to clean because the offline step above did it
              cleanContents: false
              preservePaths: true

          - task: PowerShell@2
            displayName: 'Delete app_offline.htm file'
            inputs:
              targetType: 'inline'
              script: |
                # Get credentials from variable group
                $ftpServer = "$(FtpServer)"
                $ftpUsername = "$(FtpUsername)"
                $ftpPassword = "$(FtpPassword)"
                
                $ftpUri = "ftp://$ftpServer/httpdocs/app_offline.htm"
                $ftpRequest = [System.Net.FtpWebRequest]::Create($ftpUri)
                $ftpRequest.Method = [System.Net.WebRequestMethods+Ftp]::DeleteFile
                $ftpRequest.Credentials = New-Object System.Net.NetworkCredential($ftpUsername, $ftpPassword)
                $ftpRequest.EnableSsl = $false
                try {
                  $response = $ftpRequest.GetResponse()
                  Write-Host "app_offline.htm deleted successfully"
                  $response.Close()
                } catch {
                  Write-Host "Error deleting app_offline.htm: $_"
                }
          